### ISSUE TITLE
wrong type of quote in readme file

### ISSUE THREAD

**Issue by alejandroerickson** [vapniks/org-dotemacs#12]
This is nitpicky for sure, but if you format the eslisp in "Add (require ‘org-dotemacs) in your ~/.emacs file" you'll get the correct type of single quote and others won't get an error when they copy this into their init file.

I'll just test to see if it makes a difference here

(require 'org-dotemacs)

`(require 'org-dotemacs)`
##

**Comment by vapniks** [comment]
good point. I'm using org-mode not markdown, but I will see what I can do.
