### ISSUE TITLE
org-dotemacs on windows (..I know) fails on the site-start<2> filename

### ISSUE THREAD

**Issue by sanderboer** [vapniks/org-dotemacs#3]
Hi,

I have org-dotemacs working on linux, but my windows machine fails when the script temporarily writes out the buffer to site-start<2>, the buffer with this name is created but windows' filesystem canot handle the brackets.

windows 7, emacs 24.3.1, latest package via package manager version 2013.09.09.156

cheers,
Sander
##

**Comment by vapniks** [comment]
working on it..

**Comment by neildurant** [comment]
I hacked in a fix for this locally, but It's not very pleasant and probably isn't the right fix.  But it allows me to keep working.  Thought I'd share it in case it's useful to anyone, in lieu of a proper fix.  This is a diff of org-dotemacs.el:

```
@@ -565,11 +566,12 @@
                 matchbuf (org-dotemacs-extract-subtrees (or org-dotemacs-tag-match match)))
           (with-current-buffer matchbuf
             ;; Hack: write the buffer out first to prevent org-babel-pre-tangle-hook
             ;; prompting for a filename to save it in.
-            (write-file (concat temporary-file-directory (buffer-name)))
+            (setq temp-buffer-name (replace-regexp-in-string "<[0-9]*>" "" (buffer-name)))
+            (write-file (concat temporary-file-directory (temp-buffer-name)))
             (org-dotemacs-load-blocks target-file error-handling)
-            (delete-file (concat temporary-file-directory (buffer-name))))
+            (delete-file (concat temporary-file-directory (temp-buffer-name))))
           (kill-buffer matchbuf))
         (unless visited-p
           (kill-buffer to-be-removed))))))
```

**Comment by ddewaleffe** [comment]
Go hit by that too. It is probably better to use (make-temp-file "name"). Proposed fix doesn't take care of other special characters and potentially pollutes working directory
			       (let ((tmpfilname (make-temp-file "orgdotemacs")))
				 (write-file tmpfilname)
				 (org-dotemacs-load-blocks  target-file error-handling)
			         (delete-file tmpfilname)))

**Comment by vapniks** [comment]
I've rewritten the code so it no longer uses tmp files and just maps over the source code blocks directly. This has made the code much shorter, and should fix the problems you mention.
