### ISSUE TITLE
Add a small example to the readme?

### ISSUE THREAD

**Issue by Trevoke** [vapniks/org-dotemacs#4]
It'd be nice to see one way the pieces can be put together :)

**Comment by vegetableman** [comment]
:+1:

**Comment by vapniks** [comment]
I have added a file dotemacs-test.org to show how it should work.

**Comment by Trevoke** [comment]
Nice, thanks :)

**Comment by vapniks** [comment]
the code might not be in a workable state at the moment though.. should be updated in a few days
