### ISSUE TITLE
org-dotemacs-load-file doesn't behave as expected

### ISSUE THREAD

**Issue by oddious** [vapniks/org-dotemacs#6]
After the most recent update from Melpa the functionality seems to be broken as the following piece of code doesn't produce an output file:
`(org-dotemacs-load-file "enabled" "~/org/config/dotemacs.org" "~/org/config/dotfiles/home/.emacs.d/elisp/dotemacs.el")`.
Although an output can be produced by `org-dotemacs-load-blocks`, this functions doesn't match tags despite what is declared in specs and ommiting of unwanted code blocks must be achieved with `:tangle no` option.

The version from 24.12.2014 works as expected.
##

**Comment by vapniks** [comment]
working on it

**Comment by vapniks** [comment]
This should be fixed now.
