### ISSUE TITLE
Exclusion tag match doesn't work with 2nd level headings?

### ISSUE THREAD

**Issue by LeoUfimtsev** [vapniks/org-dotemacs#8]
Hello, 

I want to exclude certain code when launching emacs in terminal.  

If I launch emacs like:  

```
emacs --tag-match "-gui" -mm
```

Then this section still get's loaded although I did not want :gui: tagged heads to be loaded:

```
* Config 
** Menu Bar                      :gui:
 #+begin_src
 ..... menu items code
#+end_src
```

But if it's on the first level, then it doesn't get loaded.

```
* Menu Bar   :gui:
```

It took a while to figure out. It would be nice for this to either be fixed or documented.

Otherwise great mode. Thank you so much for your hard work.
##

**Comment by alejandroerickson** [comment]
I experienced this as well when using the "BROKEN" tag at the second level.  Is this fixed on any of the forks?

**Comment by TinaRussell** [comment]
I haven’t used tag exclusion or inclusion, but I’ve found org-dotemacs to ignore the “BROKEN” todo state, on any level; I tried putting my whole “Packages” heading (a level 1 heading with dozens of subheadings) as “BROKEN” and org-dotemacs happily loaded every single block.
(I can share my init file and org-dotemacs file, if that’s needed to help solve the problem.)

**Comment by vapniks** [comment]
This should be fixed now.
Let me know if you still have problems.
